# Generated by Django 5.2.10 on 2026-02-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('format', models.CharField(choices=[('N', 'Novel'), ('S', 'Short Story'), ('B', 'Biography'), ('E', 'Essays'), ('D', 'Drama'), ('P', 'Poetry')], max_length=1)),
                ('genre', models.CharField(choices=[('F', 'Fantasy'), ('R', 'Romance'), ('H', 'Horror'), ('S', 'Science Fiction'), ('M', 'Mystery'), ('T', 'Thriller'), ('H', 'Historical Fiction'), ('A', 'Adventure')], max_length=1)),
                ('price', models.BigIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
