# Generated by Django 5.2.10 on 2026-02-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
